name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # ou a branch padrão do seu repositório

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: . # ou a pasta onde está seu site (ex: ./public)
      - uses: actions/deploy-pages@v4